### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TexBlock** [ThinkingStudios/RyoamicLights#18]
- [ ] fix entrypoint compat 
- [x] #21
- [x] #28
- [x] move to yarn mappings
- [x] rewrite get instance method
- [x] Library: architectury-api -> platform native api
- [x] Gradle plugin: `me.shedaniel.unified-publishing` -> `com.hypherionmc.modutils.modpublisher`
- [x] Feature: #16 
- [ ] Try fix #11 (maybe need mixin [`ForgeModelBlockRenderer`](https://github.com/MinecraftForge/MinecraftForge/blob/1.20.x/src/main/java/net/minecraftforge/client/model/lighting/ForgeModelBlockRenderer.java))
