### ISSUE TITLE
Incompatible mods

### ISSUE THREAD

**Issue by TexBlock** [ThinkingStudios/RyoamicLights#6]
- [x] [Ars Nouveau](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau) #3 (fixed in `0.1.5+1.20.1`/`0.1.4+1.19.4`/`0.1.4+1.19.3`/`0.1.4+1.19.2`/`0.1.4+1.18.2`/`0.1.5+1.16.5`)
- [x] ModernFix(dynamic resource) #9 
- [ ] Forge lighting pipeline #11

**Comment by kakashi1464** [comment]
https://cdn.discordapp.com/emojis/889959355045277756.gif?size=96&quality=lossless

**Comment by kakashi1464** [comment]
s∞n

**Comment by Polarite** [comment]
https://github.com/LambdAurora/LambDynamicLights/issues/231
this issue with nvidium still persists with this fork, this issue doesnt crash the game yet slowing down the chunk loading.

**Comment by TexBlock** [comment]
> [LambdAurora#231](https://github.com/LambdAurora/LambDynamicLights/issues/231) this issue with nvidium still persists with this fork, this issue doesnt crash the game yet slowing down the chunk loading.

I not have nvidia GPU for test
